/*
 * This file belongs to Hoist, an application development toolkit
 * developed by Extremely Heavy Industries (www.xh.io | info@xh.io)
 *
 * Copyright © 2026 Extremely Heavy Industries Inc.
 */
package io.xh.hoist.security.crypto

import spock.lang.Specification

/**
 * Verifies {@link LegacyJasyptDecrypter} correctly reproduces the decode side of jasypt 1.9.3's
 * {@code BasicTextEncryptor} and {@code BasicPasswordEncryptor} default algorithms.
 *
 * <p>Test vectors below were generated by jasypt 1.9.3 itself on a standalone JVM (the failure
 * mode that originally motivated the jasypt removal manifests only under Spring Boot's launcher
 * classloader; standalone JVMs run jasypt fine). The generator script is preserved in the
 * fixtures repo under {@code .planning} — see {@code src/test/groovy/README.md}.
 */
class LegacyJasyptDecrypterSpec extends Specification {

    // Same password historically hard-coded in AppConfig.groovy for `pwd` value encryption.
    private static final String APPCONFIG_PWD = 'dsd899s_*)jsk9dsl2fd223hpdj32))I@333'

    // 'caf' + U+00E9 (precomposed é)
    private static final String CAFE_NFC = 'caf' + new String([0x00E9] as int[], 0, 1)
    // 'caf' + U+0065 'e' + U+0301 combining acute accent
    private static final String CAFE_NFD = 'caf' + new String([0x0065, 0x0301] as int[], 0, 2)

    def 'decrypts known jasypt BasicTextEncryptor fixtures'() {
        given:
        def decrypter = new LegacyJasyptDecrypter(APPCONFIG_PWD)

        expect:
        decrypter.decrypt(ciphertext) == plaintext

        where:
        label                | plaintext                                        | ciphertext
        'simple ascii'       | 'hello world'                                    | 'sYvsDA6GhTFy97SLuc8I3La99s6fkC8S'
        'simple ascii 2'     | 'roundtrip-test'                                 | '0WLuQW9MxI0qPNOqTwVT60ZPGDl/QU0Y'
        'unicode passthrough'| 'café é résumé'                                  | 'HNy2JIeH4NnJdyzFJ9hS+lzfPBtbF43fyWrHL/l2YI0='
        'empty string'       | ''                                               | 'cjMjCRe97tekyE0aIYo6QQ=='
        'single ascii char'  | 'a'                                              | 'phwH8NviH8ZnT5aKxCB1Mw=='
        'long (256 chars)'   | 'X' * 256                                        | '+HtRuPOLYBznPrb5ODVMOcGLi3Fd+iQ0d5TbKBbAkpDbF4HTEOZISPiNwIXg3ri8pfk6p3zLsPiAEgdnw7EDUQ6p47cUSAejI4TF9d08GVXJqoIjRH9NJt5yUsYj2rQMpWYpKmJpIFzKktOarwdUr/MuXMQeJnVEpHKY+bOa3D818AuRib5DtsAYrMCF+Zyqe2J6Ag5c6Gg4OAdTCumN0EJxHMclzWjOD3sj9DWdTs7s17D5iCCITV4mu4/wMiPTNDUiRP5OLuj8Zl4pNfXmBS6op7yCXbOBd9lA6PEltSkDrzwPy6o9uSDt2qlpiDNkM4qtCjsY/XBQVw1NaOrBdMiZtLEIfW/ijYhsutZwsCk='
        'unicode NFC (café)' | CAFE_NFC                                         | 'T2lm+RPHDniI+WHIsk4jTA=='
        'unicode NFD (café)' | CAFE_NFD                                         | '1fK4n5KiCvZFeMvkXHvK+A=='
        'whitespace+special' | 'a b c\n!@#$%^&*()'                              | '45XphHP8xnG0uQb3oIqmSgcAgpa2VwxdjoHQAbjfYMs='
    }

    def 'text decrypt preserves the exact codepoint sequence (BasicTextEncryptor normalizes only the password, not the plaintext)'() {
        // Confirms NFC and NFD plaintexts round-trip distinctly through jasypt — the legacy text
        // path does NOT touch plaintext bytes. (The password digest path DOES NFC-normalize the
        // input; that contract is exercised separately below.)
        given:
        def decrypter = new LegacyJasyptDecrypter(APPCONFIG_PWD)

        expect:
        decrypter.decrypt('T2lm+RPHDniI+WHIsk4jTA==') == CAFE_NFC
        decrypter.decrypt('1fK4n5KiCvZFeMvkXHvK+A==') == CAFE_NFD
        CAFE_NFC != CAFE_NFD
        CAFE_NFC.length() == 4
        CAFE_NFD.length() == 5
    }

    def 'rejects too-short ciphertext'() {
        given:
        def decrypter = new LegacyJasyptDecrypter(APPCONFIG_PWD)

        when:
        decrypter.decrypt(Base64.encoder.encodeToString(new byte[4]))

        then:
        thrown(IllegalArgumentException)
    }

    def 'matches known jasypt BasicPasswordEncryptor digest fixtures'() {
        // BasicPasswordEncryptor uses a per-call random salt, so each encoding line is a different
        // fixture of the SAME plaintext. The empty/single-char/long/unicode/whitespace cases
        // exercise corner inputs that previously surfaced bugs in similar reimplementations.
        expect:
        LegacyJasyptDecrypter.matchesLegacyPasswordHash(plain, encoded)

        where:
        label                  | plain                | encoded
        'simple ascii a'       | 'secret'             | 'Dn9nYr0xRJwMqmobJYydHNEVGYXDuuRv'
        'simple ascii b'       | 'secret'             | '4ZciBiDn8vFKS7KfWKDtrPI2zh65npVq'
        'simple ascii c'       | 'secret'             | '3vCC8qlzR40smcGfXLA795dxcnyRNmoS'
        'simple ascii d'       | 'secret'             | 'mWwYfNJOQyvOVIFEVFJkgro8OyZjvNM4'
        'password'             | 'password'           | 'FJ4Cw1xTfDMVAHFv1bmv7OZmSsKnieZD'
        'playwright fixture'   | 'playwright-test'    | '3hrIc7ebBL/NxnkkVk0OWUAMyxRVld3U'
        'empty string'         | ''                   | 'ChrU+FtaJNXpOqOvR2/MYCCGU/hILcyS'
        'single char'          | 'a'                  | '7DJDajtcTZ6jShReh/inrfJ5ZXCitGfr'
        'long (256 chars)'     | 'X' * 256            | 'sdvN0Lh8lNANx56RJlYycFBxvbieeoU+'
        'unicode NFC (café)'   | CAFE_NFC             | '5skexPacgCES39VwmXE3aH7vIzKBWb7s'
        'unicode NFD (café)'   | CAFE_NFD             | 'dr9D3fwsSqy/7hE6gJeEbodx7TI5gpTC'
        'whitespace+special'   | 'a b c\n!@#$%^&*()'  | 'KUJ3pGX2vEbcCgE5Wck4b9m7mFV8e89n'
    }

    def 'NFC-encoded digest verifies an NFD plaintext (jasypt-compatible NFC normalization)'() {
        // The encoded fixture below was generated from the NFC form of "café". The NFD form is
        // a distinct codepoint sequence but normalizes to the same NFC form before hashing, so
        // verification must succeed.
        expect:
        LegacyJasyptDecrypter.matchesLegacyPasswordHash(CAFE_NFD, '5skexPacgCES39VwmXE3aH7vIzKBWb7s')
    }

    def 'rejects wrong plaintext for legacy digest'() {
        expect:
        !LegacyJasyptDecrypter.matchesLegacyPasswordHash('wrong', 'Dn9nYr0xRJwMqmobJYydHNEVGYXDuuRv')
        !LegacyJasyptDecrypter.matchesLegacyPasswordHash('SECRET', 'Dn9nYr0xRJwMqmobJYydHNEVGYXDuuRv')
        !LegacyJasyptDecrypter.matchesLegacyPasswordHash('', 'Dn9nYr0xRJwMqmobJYydHNEVGYXDuuRv')
        !LegacyJasyptDecrypter.matchesLegacyPasswordHash(null, 'Dn9nYr0xRJwMqmobJYydHNEVGYXDuuRv')
        !LegacyJasyptDecrypter.matchesLegacyPasswordHash('secret', null)
    }

    def 'looksLikeLegacyPasswordHash recognises 24-byte base64 strings'() {
        expect:
        LegacyJasyptDecrypter.looksLikeLegacyPasswordHash('Dn9nYr0xRJwMqmobJYydHNEVGYXDuuRv')
        LegacyJasyptDecrypter.looksLikeLegacyPasswordHash('3hrIc7ebBL/NxnkkVk0OWUAMyxRVld3U')

        and: 'rejects non-base64, wrong length, null, BCrypt-shaped'
        !LegacyJasyptDecrypter.looksLikeLegacyPasswordHash(null)
        !LegacyJasyptDecrypter.looksLikeLegacyPasswordHash('')
        !LegacyJasyptDecrypter.looksLikeLegacyPasswordHash('not-base64-!!!')
        !LegacyJasyptDecrypter.looksLikeLegacyPasswordHash('$2a$10$abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123')
        !LegacyJasyptDecrypter.looksLikeLegacyPasswordHash(Base64.encoder.encodeToString(new byte[16]))
    }
}
